# Site settings
title: Risan Bagja
description: >-
  Programming journal of Risan Bagja Pradana. A passionate coder who writes
  codes for fun. Seriously.

# Url settings
permalink: /blog/:title:output_ext

collections:
  tips:
    output: true

# Theme settings
theme_settings:
  lang: en
  date_format: "%-d %b %Y"
  google_analytics: UA-27136969-15
  disqus_website_name: risanb
  menu_pages:
    -
      path: blog.md
      title: Blog
    -
      path: tips.md
      title: Tips
    -
      path: about.md
      title: About
  footer_links:
    -
      title: Github
      url: "https://github.com/risan"
    -
      title: Twitter
      url: "https://twitter.com/risanbagja"
    -
      title: Stack Overflow
      url: "https://stackoverflow.com/users/5138222"

# Markdown settings
markdown: kramdown
highlighter: rouge

# Build settings
safe: true
sass:
  style: compressed
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

# Default front matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      comments: false
      image:
        path: /img/default-og.jpg
        width: 1200
        height: 800
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: "tips"
    values:
      layout: post
      comments: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap

# jekyll-feed plugin settings
feed:
  collections:
    - tips

# jekyll-seo-tag plugin settings
lang: en_US
author:
  twitter: risanbagja
twitter:
  username: risanbagja
  card: summary_large_image
logo: /img/risan-square.jpg
social:
  name: Risan Bagja Pradana
  links:
    - https://twitter.com/risanbagja
    - https://github.com/risan
