# Site settings
title: Risan Bagja
description: >-
  Programming journal of Risan Bagja Pradana. A passionate coder who writes
  codes for fun. Seriously.

# Url settings
baseurl: ""
url: ""
permalink: /blog/:title:output_ext

# Theme settings
theme_settings:
  lang: en
  date_format: "%-d %B %Y"
  menu_pages:
    -
      path: blog.md
      title: Blog
    -
      path: about.md
      title: About
  footer_links:
    -
      title: Github
      url: "https://github.com/risan"
    -
      title: Twitter
      url: "https://twitter.com/risanbagja"
    -
      title: Stack Overflow
      url: "https://stackoverflow.com/users/5138222"

# Markdown settings
markdown: kramdown
highlighter: rouge

# Build settings
safe: true
strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: true
sass:
  style: compressed
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      image:
        path: /img/default-og.jpg
        width: 1200
        height: 800
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      image:
        path: /img/default-og.jpg
        width: 1200
        height: 800
  -
    scope:
      path: "google*.html"
    values:
      sitemap: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# jekyll-seo-tag plugin settings
lang: en_US
author:
  twitter: risanbagja
twitter:
  username: risanbagja
  card: summary_large_image
logo: /img/risan-square.jpg
social:
  name: Risan Bagja Pradana
  links:
    - https://twitter.com/risanbagja
    - https://github.com/risan
